name: models
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.3

dependencies:
  uuid: ^4.2.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
