name: services
description: Application services
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.2.3

dependencies:
  models:
    path: ../models

  riverpod: ^2.4.9

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
