name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  flutter-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Init Hermit
        uses: cashapp/activate-hermit@v1

      - name: Install Dependencies
        run: make get

      - name: Run Flutter Analyze
        run: make analyze

      - name: Run Flutter Test
        run: make test
